<a href="https://colab.research.google.com/github/MaximSS1309/ML_SEREDOVSKIJ_MAXM/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:

a = np.array([2, 4, 6, 8, 10])
type(a)

numpy.ndarray

### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
a = np.zeros(10)
b = np.ones(8)
c = np.full(6,7)


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
a = np.arange(1,21).reshape(4,5)
print(a)
b = np.arange(2,21,2)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
a = np.linspace(0, 1, 11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:

a = np.arange(1,13)
print(a)
b = np.arange(1,13).reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:

b = np.arange(1,13).reshape(3,4)
print(f"Кількість вимірів: {b.ndim}")
print(f"Форма: {b.shape}")
print(f"Загальна кількість елементів: {b.size}")
print(f"Тип даних елементів: {b.dtype}")

Кількість вимірів: 2
Форма: (3, 4)
Загальна кількість елементів: 12
Тип даних елементів: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
a = np.array([1.2, 3.5, 5.7, 7.9])
new_a = a.astype(int)
print(new_a)


[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(a[0])
print(a[-1])
print(a[range(1,6)])
print(a[::2])

10
80
[20 30 40 50 60]
[10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [10]:
import numpy as np

a = np.array([[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]])
print(a[1, 2])
print(a[1])
print(a[:, 2])
print(a[1:, :2])

7
[5 6 7 8]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [18]:
a = np.arange(1, 16)
a[5:10] = 0
print(a)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [26]:
a = np.array([4, 8, 15, 16, 23, 42])

print(sum(a))
print(np.mean(a))
print(min(a))
print(max(a))
print(np.median(a))
print(np.std(a))

108
18.0
4
42
15.5
12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [31]:
a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
print(sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
print(np.mean(a, axis=0))


[12 15 18]
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [39]:
a = np.arange(1, 11)
print(a ** 2)
print(np.sqrt(a))
print(np.log(a))


[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [40]:
a = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print(a>15)
print(a % 2 == 0)
print(a >= 10, a <= 30)


[False False False  True  True  True  True  True]
[False False  True  True False False  True  True]
[False False  True  True  True  True  True  True] [ True  True  True  True  True  True  True False]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [41]:
a = np.array([-5, 3, -2, 8, -1, 10, 0])
a[a<0] = 0
print(a)


[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [43]:
np.random.seed(42)
a = np.random.randint(0, 101, size=20)
gt_50 = np.sum(a > 50)
lte_50 = np.sum(a <=50)
print(a)
print(gt_50)
print(lte_50)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
12
8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [47]:
a = np.arange(1, 25)
m1 = a.reshape(4, 6)
print("Матриця 4x6:\n", m1)
print("Shape:", m1.shape)
m2 = a.reshape(6, 4)
print("Матриця 6x4:\n", m2)
print("Shape:", m2.shape)
m3 = a.reshape(2, 3, 4)
print("Тривимірний масив 2x3x4:\n", m3)
print("Shape:", m3.shape)

1. Матриця 4x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
2. Матриця 6x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)
3. Тривимірний масив 2x3x4:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [48]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
v_concat = np.vstack((A, B))
h_concat = np.hstack((A, B))
print("вертикально",v_concat)
print("горизонтально", h_concat)

вертикально [[1 2]
 [3 4]
 [5 6]
 [7 8]]
горизонтально [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [49]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
flat_arr = a.flatten()
print(flat_arr)
rav_arr = a.ravel()
print(rav_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [50]:


a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)
print(a - b)
print(a * 3)
print(b * 3)


[ 3  7 11]
[1 1 1]
[ 6 12 18]
[ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))
print(a @ b)


32
32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:


v = np.array([3, 4])

norm = np.linalg.norm(v)
print(norm)

v_norm = v / norm
print(v_norm)

### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [52]:
a = [1, 0, 0]
b = [0, 1, 0]
print(np.cross(a, b))


[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [53]:

a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos_angle)

angle_deg = np.degrees(np.arccos(cos_angle))
print(angle_deg)


0.7999999999999998
36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [56]:


A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)
print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [57]:


A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

#перемножуються відповідні елементи
print(A * B)

#рядок на стовпець
print(A @ B)


[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [58]:
A = np.array([[4, 7],
              [2, 6]])

det = np.linalg.det(A)
print(det)

A_inv = np.linalg.inv(A)
print(A_inv)

print(A @ A_inv)

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [59]:
A_eq = np.array([[2, 1],
                 [1, 3]])
b_eq = np.array([5, 6])

x = np.linalg.solve(A_eq, b_eq)
print(x)

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [60]:

I = np.eye(4)
print(I)

X = np.random.randint(1, 10, (4, 4))
print(X @ I)
print(np.array_equal(X @ I, X))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 5. 1. 6.]
 [9. 1. 3. 7.]
 [4. 9. 3. 5.]
 [3. 7. 5. 9.]]
True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [61]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A + 10)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [62]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])

res = A + v
print(res)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [63]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)

Z = (A - mu) / sigma
print(Z)


[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:

np.random.seed(42)

a1 = np.random.randint(1, 101, 10)
print(a1)

a2 = np.random.rand(3, 3)
print(a2)

a3 = np.random.randn(1000)

print(np.mean(a3))
print(np.std(a3))


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [64]:


scores = np.random.randint(0, 101, 30)

print(np.mean(scores))
print(np.median(scores))
print(np.max(scores), np.min(scores))
print(np.sum(scores >= 60))
print(np.mean(scores >= 90) * 100)


43.8
47.5
92 1
9
6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [65]:


sales = np.array([[120, 150, 170, 160],
                  [80, 90, 100, 110],
                  [200, 180, 210, 230]])

# 1
print(np.sum(sales, axis=1))

# 2
print(np.sum(sales, axis=0))

# 3
print(np.argmax(np.sum(sales, axis=1)))

# 4
print(np.argmax(np.sum(sales, axis=0)))

# 5
print(np.mean(sales, axis=1))


[600 380 820]
[400 420 480 500]
2
3
[150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [66]:

matrix = np.random.randint(1, 21, (5, 5))

print(np.trace(matrix))
print(np.trace(np.fliplr(matrix)))
print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))

matrix[matrix < np.mean(matrix)] = 0
print(matrix)

68
41
[18 16 18 15 12]
[7 9 1 8 1]
[[18 12  0  0  0]
 [14 16 15  0 14]
 [ 0 16 13 18 15]
 [13  0 15 13  0]
 [ 0  0  0 12  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

print(np.linalg.norm(X[0] - X[1]))
print(np.linalg.norm(X[0] - X[2]))
print(np.linalg.norm(X[1] - X[2]))

### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
A = np.random.randint(1, 10, (4, 4))

norms = np.linalg.norm(A, axis=1, keepdims=True)
A_norm = A / norms

print(A_norm)


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [67]:


A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
print(x)

check = A @ x
print(check)

print(np.allclose(check, b))


[ 2.22222222  3.44444444 -0.11111111]
[9. 8. 3.]
True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
